### ISSUE TITLE
Failed to load 'Assets/plugins/VIOSO/VIOSOWarpBlend64.dll', expected x64 architecture, but was Unknown architecture.

### ISSUE THREAD

**Issue by Root-107** [Ahmed-jerbi/VIOSO-Unity-HDRP#1]
Encounter this error when importing assets in to test HDRP project, details bellow.

Error message:
```
Failed to load 'Assets/plugins/VIOSO/VIOSOWarpBlend64.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```
Unity version:
2021.3.10f1 LTS

**Comment by Ahmed-jerbi** [comment]
Please try reverting to the previous (.dll) version: https://github.com/Ahmed-jerbi/VIOSO-Unity-HDRP/commits/master/Assets/Plugins/Vioso/VIOSOWarpBlend64.dll

**Comment by Barbelot** [comment]
Hello,
I have same error (latest .dll and Unity 2022.2.11).
I tried reverting to older dll versions but I get the same error.

**Comment by Barbelot** [comment]
I got it working with the custom dll you gave me during our last formation @Ahmed-jerbi .
In case it helps someone this dll can be downloaded [here](http://gofile.me/67omf/IxjCGmZl0).

**Comment by Root-107** [comment]
> I got it working with the custom dll you gave me during our last formation @Ahmed-jerbi . In case it helps someone this dll can be downloaded [here](http://gofile.me/67omf/IxjCGmZl0).

Hey,

Sorry left this for a while, is there any chance of getting hold of that DLL. The download link goes to 'page not found' probably because I have left it so long.

**Comment by Barbelot** [comment]
Sure, you can find it in our [Unity HDRP Vioso Template](https://github.com/Theoriz/Unity-HDRP-Vioso-Template) (in Assets/Plugins/Vioso).

**Comment by Root-107** [comment]
All working thank you 👍
